backend:
  name: github
  repo: axrez/axrez.github.io
  branch: od
media_folder: src/images
public_folder: /static/assets
collections:
  - name: "pages"
    label: "Pages"
    delete: false
    files:
    - label: "Front Page"
      name: "front-page"
      file: "src/markdown/index.md"
      fields:
      - { label: Path - Advanced users only, name: path, widget: string }
      - { label: Title, name: title, widget: string }
      - { label: Intro, name: intro, widget: markdown }         
    - label: "About"
      name: "about"
      file: "src/markdown/about.md"
      fields:
      - { label: Path - Advanced users only, name: path, widget: string }
      - { label: Head, name: head, widget: string }
      - { label: Body, name: body, widget: markdown }
    - label: "Work"
      name: "work"
      file: "src/markdown/work.md"
      fields:
      - { label: Path - Advanced users only, name: path, widget: string }
      - { label: Head, name: head, widget: string }
      - { label: Body, name: body, widget: markdown }