backend:
  name: github
  repo: axrez/axrez.github.io
media_folder: src/images
public_folder: /static/assets
collections:
  - name: "pages"
    label: "Pages"
    delete: false
    files:
    - label: "Front Page"
      name: "front-page"
      file: "src/markdown/index.md"
      fields:
      - { label: Path - Advanced users only, name: path, widget: string }
      - { label: Title, name: title, widget: string }
      - { label: Intro, name: intro, widget: markdown }