backend:
  name: test-repo
media_folder: static/assets
public_folder: /static/assets
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Front Page"
      name: "front-page"
      file: "src/pages/index.md"
      fields:
      - { label: Title, name: title, widget: string }
      - { label: Intro, name: intro, widget: markdown}